config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: "users#show", as: :authenticated_root
  end

  root to: 'homes#index'

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }

  resources :users, only: [:show, :index]

  resources :friendships, only: [:create, :update, :destroy]

  resources :courses, only: [:new, :index, :create, :show]

  resources :users, only: :show do
    resources :friendships, only: :index
    resources :posts, only: :create
    resources :rounds, only: :create
    resources :courses, only: :create
  end

  resources :courses, only: :show do
    resources :tees, only: :create
  end


  resources :rounds, only: [:new, :index, :create, :show]

  resources :rounds, only: :show do
    resources :player_rounds, only: [:index, :create]
  end
  namespace :api do
    namespace :v1 do
      resources :courses, only: [:index, :show]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :cover_image, CoverImageUploader
  mount_uploader :profile_photo, ProfilePhotoUploader

  has_many :rounds
  has_many :player_rounds
  has_many :courses
  has_many :tees
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  DIFF_HASH = {
    5 => 1,
    6 => 1,
    7 => 2,
    8 => 2,
    9 => 3,
    10 => 3,
    11 => 4,
    12 => 4,
    13 => 5,
    14 => 5,
    15 => 6,
    16 => 6,
    17 => 7,
    18 => 8,
    19 => 9,
    20 => 10
  }.freeze

  def full_name
    first_name && last_name ? first_name + " " + last_name : "Add your full name"
  end

  def not_scored_rounds(rounds_count=3)
    not_scored = []
    rounds = self.rounds.includes(:player_rounds).includes(:course)
    rounds.where("round_date < ?", Date.today).to_a.keep_if { |r| r.unscored?}
  end

  def upcoming_rounds
    rounds.includes(:course).where("round_date > ?", Date.today)
  end

  def handicap
    return "You need to play #{5 - rounds.count} more rounds to calculate a handicap." if rounds.count < 5

    differentials = get_differentials

    usable_differentials = []
    diff_count = differentials.length

    n = DIFF_HASH[diff_count] rescue ArgumentError
    n.times{ usable_differentials << differentials.shift }
    ( usable_differentials.inject(0) { |sum, number| sum + number } / usable_differentials.length * 0.96 ).round(2)
  end

  def course_rounds(course)
    upcoming_rounds.where(course_id: course.id)
  end

  def accepted_friends
    friendships.where(user_id: self.id, accepted: true) || friendships.where(friend_id: self.id, accepted: true)
  end

  def friendship_pending_with(other_user)
    friendships.find_by(accepted:false, friend_id: other_user.id)
  end

  def pending_friendships(current_user)
    Friendship.where(friend_id: current_user.id, accepted: false, ignored: false)
  end

  private

  def usable_rounds
    player_rounds
      .includes(:round)
      .includes(:tee)
      .sort_by { |player_round| player_round.date }
      .reverse
      .last(20)
  end

  def get_differentials
    differentials = []
    usable_rounds.each do |round|
      differentials << (round.score - round.tee.rating) * 113 / round.tee.slope
    end
    differentials.sort!
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def create
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        sign_up(resource_name, resource)
        if params[:user][:profile_photo].present?
          flash[:notice] = "Thanks for signing up! Now please set your profile picture!"
          render "crop"
        else
          respond_with resource, location: after_sign_up_path_for(resource)
        end
      end
    else
      clean_up_passwords resource
      render 'homes/index'
    end
  end

  def update
    account_update_params = devise_parameter_sanitizer.sanitize(:account_update)
    @user = User.find(current_user.id)
      successfully_updated = if account_update_params[:password].blank?
        params[:user].delete(:current_password)
        @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
      else
        @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
      end

      if successfully_updated
        if params[:user][:profile_photo].present?
          render "crop"
        else
          set_flash_message :notice, :updated
          sign_in @user, :bypass => true
          redirect_to user_path(resource)
        end
      else
        render "edit"
      end
  end

  protected

  def after_update_path_for(resource)
    user_path(resource)
  end

  private

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def account_update_params
    devise_parameter_sanitizer.sanitize(:account_update)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  protected

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:player_query].present?
      @users = User.search(params[:player_query])
    else
      @users = User.all
    end
  end

  def show
    if params[:id]
      @user = User.includes(:player_rounds).find(params[:id])
    else
      @user = current_user
    end
    @round = Round.new
    @course = Course.new
    @post = Post.new
    @wall_posts = Post.where(recipient: @user).includes(:recipient).includes(:user)
    @friendship = current_user.friendships.where("user_id = #{@user.id} OR friend_id = #{@user.id}").first
    if current_user
      @pending_friendships = Friendship.where(friend_id: current_user.id, accepted: false, ignored: false)
    end
  end
end

app/views/users/_feed.html.haml
- @wall_posts.reverse.each do |post|
  .panel.wall_post
    .row
      .small-1.columns
        = image_tag post.user.profile_photo
      .small-11.columns
        - if post.user == post.recipient
          %h5{:style => "margin-bottom:0;"}= link_to post.user.full_name, user_path(post.user)
        - else
          %h5{:style => "margin-bottom:0;"}
            = link_to post.user.full_name, user_path(post.user)
            \&gt; #{link_to post.recipient.full_name, user_path(post.recipient)}
        %span{:style => "font-size:10px;"}
          = time_ago_in_words(post.created_at)
          ago
      .row
        .small-12.columns
          %span{:style => "margin-left:5px;"}= post.body

app/views/users/_friends.html.haml
%h3
  = @user.first_name
  's Friends
%ul.large-block-grid-3
  - @user.accepted_friends.includes(:friend).sample(6).each do |friendship|
    - if friendship.user == @user
      %li.friend-listing
        = image_tag "http://placehold.it/75", class: "avatar", alt: "placeholder"
        %br/
        = link_to friendship.friend.full_name, user_path(friendship.friend)
    - elsif friendship.friend == @user
      %li.friend-listing
        - if friendship.user.profile_photo
          = image_tag "http://placehold.it/75", class: "avatar", alt: "placeholder"
          %br/
        - else
          = image_tag "http://placehold.it/75", class: "avatar", alt: "placeholder"
        = link_to friendship.user.full_name, user_path(friendship.user)
= link_to "View all...", user_friendships_path(@user.id)

app/views/users/_friends_buttons.html.haml
- if @user == current_user
  %ul.no-bullet.right
    %li
      = link_to '<i class="fa fa-cog"></i> Edit Profile'.html_safe, edit_user_registration_path(@user), class: "button small radius right friends_button"
    - unless @user.pending_friendships(current_user).empty?
      .row
        .small-9.columns
          #friend-request-list.panel
            %ul.no-bullet
              - if signed_in?
                - @user.pending_friendships(current_user).each do |pending|
                  %li
                    = image_tag pending.user.profile_photo, size:"60x60"
                    = pending.user.full_name
                    = link_to "Accept", friendship_path(accepted: true, user_id: pending.user.id, id: pending.id), method: :put
                    | #{link_to "Ignore", friendship_path(ignored: true, id: pending.id), method: :put}
        .small-3.columns
          #friend-request-button.button.small.radius.right.friends_button
            New Friend Request!
- else
  - if signed_in?
    %ul.no-bullet.right
      - if current_user.friendship_pending_with(@user)
        %li
          .round.secondary.label.right
            Friendship Pending
          %br/
      - elsif current_user.friends.include?(@user)
        %li
          %button#friends-button.button.small.dropdown.friends_button{"aria-controls" => "drop1", "aria-expanded" => "false", "data-dropdown" => "drop1"} Friends
          %br/
          %ul#drop1.f-dropdown{"aria-hidden" => "true", "data-dropdown-content" => "", :tabindex => "-1"}
            %li= link_to "Unfriend", friendship_path(@friendship), method: :delete, data: { confirm: "Are you sure you want to unfriend #{@user.first_name}?"}
      - elsif @user.friendship_pending_with(current_user)
      - else
        %li
          = link_to "Add Friend", friendships_path(friend_id: @user), method: :post, class: "button radius right"

app/views/users/_handicap.html.haml
- if @user.handicap.class == String
  %h4.text-center Handicap:
  .progress.round
    %span.meter{:style => "width:#{@user.player_rounds.count*20}%"}
  %p.text-center= @user.handicap
- else
  %h4
    Handicap: #{@user.handicap}

app/views/users/_recently.html.haml
%table#upcoming_table.tablesorter
  %thead
    %tr
      %th Date
      %th Course
      %th Tee Time
  %tbody
    - @user.not_scored_rounds.each do |not_scored|
      %tr
        %td= not_scored.round_date.strftime("%m/%d/%Y")
        %td= not_scored.course.name
        %td
          = link_to "#{not_scored.tee_time.strftime("%I:%M%p")}", round_path(not_scored)

app/views/users/_scored.html.haml
%table#score_table.tablesorter
  %thead
    %tr
      %th Date
      %th Course
      %th Holes
      %th Score
  %tbody
    - @user.player_rounds.includes(:round).each do |played|
      %tr
        %td= played.round.round_date.strftime("%m/%d/%Y")
        %td= link_to "#{played.round.course.name}", course_path(played.round.course)
        %td= played.hole_count
        %td= played.score

app/views/users/_stats_nav.html.haml
%dl.sub-nav.tab
  %dd{"ng-class" => "{ active: tab.isSet(1) }"}
    %a{:href => "", "ng-click" => "tab.setTab(1)"} Social
  %dd{"ng-class" => "{ active: tab.isSet(2) }"}
    %a{:href => "", "ng-click" => "tab.setTab(2)"} Tee Times
  %dd{"ng-class" => "{ active: tab.isSet(3) }"}
    %a{:href => "", "ng-click" => "tab.setTab(3)"} Finished Rounds
  %dd{"ng-class" => "{ active: tab.isSet(4) }"}
    %a{:href => "", "ng-click" => "tab.setTab(4)"} Scores

app/views/users/_upcoming.html.haml
%table#upcoming_table.tablesorter
  %thead
    %tr
      %th Date
      %th Course
      %th Tee Time
  %tbody
    - @user.upcoming_rounds.each do |upcoming|
      %tr
        %td= upcoming.round_date.strftime("%m/%d/%Y")
        %td= upcoming.course.name
        %td
          = link_to "#{upcoming.tee_time.strftime("%I:%M%p")}", round_path(upcoming)
- if @user == current_user
  %a{"data-reveal-id" => "new-round-modal", :href => "#", id: 'new-tee-time-button'} Add A New Tee Time
#new-round-modal.reveal-modal{"data-reveal" => ""}
  = render "rounds/new"
  %a.close-reveal-modal ×
#secondModal.reveal-modal{"data-reveal" => ""}
  = render "courses/new"
  %a.close-reveal-modal ×

- if flash[:notice]
  :javascript
    document.getElementById('new-tee-time-button').click();

app/views/users/_wall_post_form.html.haml
.panel
  %h3 Smack Talk
  = simple_form_for [@user, @post] do |f|
    = f.input :body, label: "Wall Post"
    = f.submit "Post", class: "button tiny radius"

app/views/users/index.html.haml
- if params[:player_query]
  %h1 Player Search
  %h4
    Your search for "#{params[:player_query]}" returned #{@users.count} result(s).
- else
  %h1 All Users
- @users.each do |user|
  .panel
    .row
      .large-4.medium-4.columns
        = image_tag user.profile_photo, size: "150x150" unless user.profile_photo == nil
      .large-8.medium-8.columns
        %h4= user.full_name
        = link_to user.email, user_path(user)
        %br/
        %h6 Handicap:
        - if user.handicap.class == String
          %h6 N/A
        - else
          %h6= user.handicap

app/views/users/show.html.haml
.cover{:style => "background:linear-gradient(rgba(0, 0, 0, 0.7),rgba(0, 0, 0, 0.7)),url(#{@user.cover_image.to_s});background-size:cover;background-position: 50% 50%;background-repeat: no-repeat;"}
%section{"ng-controller" => "TabController as tab"}
  .user-content
    .row
      .large-3.medium-3.hide-for-small.columns
        - if @user.profile_photo.url
          = image_tag @user.profile_photo.url, class: "avatar", size: "160x160", alt: "#{@user.full_name}'s profile photo"
        - else
          = image_tag "https://placeholdit.imgix.net/~text?txtsize=19&txt=#{@user.full_name}&w=160&h=160", class: "avatar", alt: "placeholder"
      .medium-8.columns
        .medium-9.columns{:style => "padding-left:0px;"}
          #sub_nav_panel.panel
            = render "users/stats_nav"
        .medium-3.columns
          = render "users/friends_buttons"
    .row
      .large-4.columns
        .panel
          %h1
            %span.title-heavy= @user.first_name
            %br/
            %span.title-light= @user.last_name
          %h6{:style => ""}
            Email: #{@user.email}
            \#{render "users/handicap"}
        #friends.panel
          = render "users/friends"
      .large-8.columns
        %div{"ng-show" => "tab.isSet(1)"}
          #wall_post_form
            = render "users/wall_post_form"
          = render "users/feed"
        .panel{"ng-show" => "tab.isSet(2)"}
          %h3.text-center Upcoming Tee Times
          - if @user == current_user && @user.upcoming_rounds.empty?
            %h6.text-center You do not have any upcoming rounds.
          = render "users/upcoming"
        .panel{"ng-show" => "tab.isSet(3)"}
          %h3.text-center Unscored Rounds
          = render "users/recently"
        .panel{"ng-show" => "tab.isSet(4)"}
          %h3.text-center Scored Rounds
          = render "users/scored"