config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: "users#show", as: :authenticated_root
  end

  root to: 'homes#index'

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }

  resources :users, only: [:show, :index]

  resources :friendships, only: [:create, :update, :destroy]

  resources :courses, only: [:new, :index, :create, :show]

  resources :users, only: :show do
    resources :friendships, only: :index
    resources :posts, only: :create
    resources :rounds, only: :create
    resources :courses, only: :create
  end

  resources :courses, only: :show do
    resources :tees, only: :create
  end


  resources :rounds, only: [:new, :index, :create, :show]

  resources :rounds, only: :show do
    resources :player_rounds, only: [:index, :create]
  end
  namespace :api do
    namespace :v1 do
      resources :courses, only: [:index, :show]
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @last_three_rounds = PlayerRound.last(3)
  end
end

app/views/homes/index.html.haml
.module
  %br/
  .row{"data-equalizer" => ""}
    .small-8.columns{"data-equalizer-watch" => ""}
      %h1.page-title Welcome to Wagglr
      %h5{:style => "color:white;"}
        Connect with your friends on and off the course. Create a league with friends,
        compete, and trash talk your buddies the next time you see them.
      - if current_user
        - if @last_three_rounds
          %ul
            - @last_three_rounds.each do |player_round|
              %li{:style => "color:white;"}
                = player_round.user.full_name
                played #{player_round.round.course.name} and shot #{player_round.score} over #{player_round.hole_count} holes!
      .row
        %blockquote.bottom
          The most important shot in golf is the next one.
          %cite Ben Hogan
    .small-4.columns{"data-equalizer-watch" => ""}
      - if current_user
        = link_to "My Dashboard", user_path(current_user), class: "button radius"
        = link_to "Add a Course", new_course_path, class: "button radius"
        = link_to "New Round", new_round_path, class: "button radius"
        %br/
        %br/
        %br/
        = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "button radius"
      - else
        .row
          #sign-in-form
            = render "devise/sessions/new"
        .row
          #sign-up-form
            = render "devise/registrations/new"